-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "1920x1280@60.005", position = "0x0", scale = 1.2, vrr = 0 })
