-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        hide_on_tablet = false,
        no_warps = true,
    },
    gestures = {
        workspace_swipe_touch = false,
    },
    input = {
        accel_profile = "adaptive",
        scroll_factor = 1.5,
        sensitivity = 0.3,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 1.3,
        },
    },
})
